### ISSUE TITLE
請教您pandora調用langchain

### ISSUE THREAD

**Issue by amakoko1** [chudaozhe/enterprise-api#2]
在https://github.com/pengzhile/pandora/issues/837 看您有成功使用pandora調用langchain

openai api试用期3个月到期，只能浏览器登录，如果要继续调用api程序代码来使用langchain该实行何种方法?已尝试https://ai.fakeopen.com/token 去生成一个fk-开头的Share Token

from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.document_loaders import TextLoader, PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import Chroma
from langchain.chat_models import ChatOpenAI
from langchain.chains import ConversationalRetrievalChain

#环境变量
import os
os.environ["OPENAI_API_KEY"] = "fk-xxxxxx"
os.environ["OPENAI_API_BASE"] = "https://ai.fakeopen.com/v1"
os.environ["OPENAI_API_PREFIX"] = "https://ai.fakeopen.com"

读取档案
file_path = "abc.pdf"
loader = file_path.endswith(".pdf") and PyPDFLoader(file_path) or TextLoader(file_path)

选择 splitter 并将文字切分成多个 chunk
splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=0)
texts = loader.load_and_split(splitter)

建立本地 db
embeddings = OpenAIEmbeddings()
vectorstore = Chroma.from_documents(texts, embeddings)

对话 chain
qa = ConversationalRetrievalChain.from_llm(ChatOpenAI(temperature=0), vectorstore.as_retriever())
chat_history = []
while True:
query = input('\nQ: ')
if not query:
break
result = qa({"question": query + ' (中文回答)', "chat_history": chat_history})
print('A:', result['answer'])
chat_history.append((query, result['answer']))

**Comment by chudaozhe** [comment]
“openai api试用期3个月到期，只能浏览器登录”我也是这种情况。我是跑通了，但我也不太懂，只能说下我的步骤：

首先我看了这个视频：https://www.bilibili.com/video/BV18X4y1t79H/，然后克隆了这个项目：https://github.com/zhaoqingpu/LangChainTest，接着做些修改，我只设置了两个环境变量
```
OPENAI_API_KEY=fk-xxxx
OPENAI_API_BASE=https://ai.fakeopen.com/v1
```
main.py
```
import argparse
import os

from langchain import PromptTemplate
from langchain.chains import RetrievalQA
from langchain.llms import OpenAI, openai
from dotenv import load_dotenv
from langchain.embeddings import HuggingFaceEmbeddings, OpenAIEmbeddings
from langchain.vectorstores import Chroma

from ChatGLM import ChatGLM

load_dotenv("config.env")
embeddings_model_name = os.environ.get("EMBEDDINGS_MODEL_NAME")
persist_directory = os.environ.get('PERSIST_DIRECTORY')
target_source_chunks = int(os.environ.get('TARGET_SOURCE_CHUNKS', 4))
openai.api_key = os.getenv("OPENAI_API_KEY")

from constants import CHROMA_SETTINGS

if __name__ == '__main__':
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
    db = Chroma(persist_directory=persist_directory, embedding_function=embeddings, client_settings=CHROMA_SETTINGS)
    retriever = db.as_retriever(search_kwargs={"k": target_source_chunks})

    llm = OpenAI(model_name="gpt-3.5-turbo")  # text-ada-001，gpt-3.5-turbo
    # llm = ChatGLM()

    prompt_template = """基于以下已知信息，简洁和专业的来回答用户的问题。
    如果无法从中得到答案，请说 "根据已知信息无法回答该问题" 或 "没有提供足够的相关信息"，不允许在答案中添加编造成分，答案请使用中文。
    已知内容:
    {context}
    问题:
    {question}"""

    promptA = PromptTemplate(template=prompt_template, input_variables=["context", "question"])
    chain_type_kwargs = {"prompt": promptA}
    qa = RetrievalQA.from_chain_type(llm=llm, retriever=retriever, chain_type="stuff",
                                     chain_type_kwargs=chain_type_kwargs, return_source_documents=True)
    while True:
        query = input("\n请输入问题: ")
        if query == "exit":
            break

        res = qa(query)
        answer, docs = res['result'], res['source_documents']

        print("\n\n> 问题:")
        print(query)
        print("\n> 回答:")
        print(answer)

        # for document in docs:
        #     print("\n> " + document.metadata["source"] + ":")

```
